fixing

diff --git a/GenPatch b/GenPatch
--- a/GenPatch
+++ b/GenPatch
@@ -1,6 +1,11 @@
 #!/usr/local/bin/zsh
 #cd /root/scripts
+echo $@ > ~/tmp
+exit
 cd /TopStor/
+TopStor='/TopStortmp'
+pace='/pace'
+web='/var/www/html/des20/'
 logging='/var/www/html/des20/Data/currentinfo2.log';
 glog='/TopStordata/TopStor.log';
 currentfw=`git branch | grep \* | awk '{print $2}'`
@@ -11,32 +16,61 @@ privilege="Uploadch";
 contrun=`./privthis.sh $privilege $userreq`;
 if [[ $contrun == 'true' ]]
 then
+ openssl  smime -decrypt -aes-256-cbc -binary -in /var/www/html/des20/$newfw -inform DER -out /TopStordata/${newfw}.tar.gz -inkey /TopStor/key/private_key.pem
+ if [ $? -ne 0 ]; then 
+ datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
+ logdata='Upgrade file is not valid ';
+ logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upnv1010@@`;
+ echo Upnv1010@$datenow@$timenow > ${logging}2;
+ dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
+ echo $datenow $timenow info $userreq  Upnv1010@@ $dtn>> $glog
+ oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
+ fi
  datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
  logdata='Start upgrading from version '$currentfw' to version '$newfw;
  logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsa1010@@@$currentfw@$newfw`;
  echo Upsa1010@$datenow@$timenow@$currentfw@$newfw > ${logging}2;
-dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
-echo $datenow $timenow info $userreq  Upsa1010@@@$currentfw@$newfw $dtn>> $glog
-oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
-
-gitloc='/TopStor';
-cd $gitloc  
-git add --all;
-currentver=`cat ver`;
-nfilever=$((filever+0));
-ncurrentver=$((currentver+0));
-#echo $filever, $ncurrentver;
-if [[ $nfilever -ge $ncurrentver ]];
-then
-#echo ok go;
-msg="committing ver"$currentver;
-git commit -am "$msg";
-git checkout -b ver$filever;
-openssl  smime -decrypt  -in $webfile/$filen -binary -inform DEM -inkey key/code2.priv  | gunzip > txt/${filever}.tar  2>&1 
-tar -xf txt/${filever}.tar
-git add --all
-msg="committing ver"$filever;
-git commit -am "$msg";
-fi 
+ dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
+ echo $datenow $timenow info $userreq  Upsa1010@@@$currentfw@$newfw $dtn>> $glog
+ oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
+ echo newfw=$newfw
+ cd /TopStordata
+ tar -xvzf ${newfw}.tar.gz
+ if [ $? -eq 0];
+ then
+  cd $TopStor
+  git commit -am "prep to apply fw ${newfw}"
+  git checkout master
+  git checkout -b ${newfw}
+  git apply /TopStordata/TopStor.p 
+  git commit -am "done applying fw ${newfw}"
+  cd $pace
+  git commit -am "prep to apply fw ${newfw}"
+  git checkout master
+  git checkout -b ${newfw}
+  git apply /TopStordata/pace.p 
+  git commit -am "done applying fw ${newfw}"
+  cd $web
+  git commit -am "prep to apply fw ${newfw}"
+  git checkout master
+  git checkout -b ${newfw}
+  git apply /TopStordata/web.p 
+  git commit -am "done applying fw ${newfw}" 
+  datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
+  logdata='Success upgrading from version '$currentfw' to version '$newfw;
+  logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upsu1010@@@$currentfw@$newfw`;
+  echo Upsu1010@$datenow@$timenow@$currentfw@$newfw > ${logging}2;
+  dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
+  echo $datenow $timenow info $userreq  Upsu1010@@@$currentfw@$newfw $dtn>> $glog
+  oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
+  rm -rf /TopStordata/*.p 2>/dev/null
+ else
+  datenow=`date +%m/%d/%Y`; timenow=`date +%T`;
+  logdata='Failed upgrading from version '$currentfw' to version '$newfw;
+  logthis=`./jsonthis3.sh Date $datenow time $timenow msg info user $userreq data $logdata code Upfa1010@@@$currentfw@$newfw`;
+  echo Upfa1010@$datenow@$timenow@$currentfw@$newfw > ${logging}2;
+  dt=${datenow}'T'${timenow}; dtn=`date +%s -d $dt`;
+  echo $datenow $timenow info $userreq  Upfa1010@@@$currentfw@$newfw $dtn>> $glog
+  oldlog=`cat $logging | sed 's/]//g'`; newlog=$oldlog,$logthis]; echo $newlog > $logging;
+ fi
 fi
-#rm $webfile/$filen
